<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="samikshagupta" name="com.todo.tests.UserController" tests="8" failures="1" timestamp="28 Jul 2021 10:54:34 GMT" time="6.837" errors="0">
  <testcase name="invalid_createUser_password" time="0.224" classname="com.todo.tests.UserController"/>
  <testcase name="invalid_loginUser_email" time="0.239" classname="com.todo.tests.UserController"/>
  <testcase name="invalid_loginUser_Password" time="0.241" classname="com.todo.tests.UserController"/>
  <testcase name="invalid_createUser_lastname" time="0.248" classname="com.todo.tests.UserController"/>
  <testcase name="invalid_createUser_email" time="0.262" classname="com.todo.tests.UserController"/>
  <testcase name="invalid_createUser_firstname" time="1.067" classname="com.todo.tests.UserController"/>
  <testcase name="loginUser" time="0.320" classname="com.todo.tests.UserController"/>
  <testcase name="createUser" time="4.236" classname="com.todo.tests.UserController">
    <failure type="java.lang.AssertionError" message="expected:&lt;406&gt; but was:&lt;201&gt;">
      <![CDATA[java.lang.AssertionError: expected:<406> but was:<201>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at com.todo.tests.UserController.createUser(UserController.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createUser -->
</testsuite> <!-- com.todo.tests.UserController -->
